trigger:
- master  # This pipeline will run whenever there are changes to the master branch.
steps:
- task: PowerShell@2
  inputs: 
    targetType: inline
    script: |
        $uri = "https://jsonplaceholder.typicode.com/posts/1"
        $response = Invoke-RestMethod -Uri $uri -Method Get
        echo $response     
