trigger:
- master  # This pipeline will run whenever there are changes to the master branch.

stages:
- stage: DeployToDev  # Define a stage called DeployToDev
  displayName: Deploy to Development Environment
  jobs:
  - job: DeployDev  # Define a job in the stage
    pool:
      vmImage: 'windows-latest'  # Specify the virtual machine image

    steps:
    - checkout: self  # Check out the source code

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '6.x'  # Specify the .NET version to use

    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'ARMSCN'  # Specify your Azure service connection
        appType: 'webApp'
        appName: 'WebApplication1'  # Specify the name of your Azure Web App
        packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'  # Path to your deployment package

- stage: DeployToStaging  # Define a stage called DeployToStaging
  displayName: Deploy to Staging Environment
  dependsOn: DeployToDev  # This stage depends on the completion of the previous stage
  condition: succeeded()  # Only run this stage if the previous stage succeeded
  jobs:
  - job: DeployStaging
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App Staging'
      inputs:
        azureSubscription: 'ARMSCN'
        appType: 'webApp'
        appName: 'WebApplication1'  # Specify the name of your staging Azure Web App
        packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
