trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
        # Define the API endpoint URL
        $uri = "https://localhost:7182/Student/getAll"

        # Send the GET request
        try {
            $response = Invoke-RestMethod -Uri $uri -Method Get

            # Output the response
            Write-Output $response

        } catch {
            # Handle errors and output a message
            Write-Error "Failed to call the API: $_"
        }
