trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    $filePath = "Common"
    if (-not (Test-Path $filePath)) {
        Write-Output "The file '$filePath' does not exist."
        exit 1  # Fail the task
    } else {
        Write-Output "The file '$filePath' exists."
    }
  displayName: 'Check File Existence'

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 5.0'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'  # Specify the version you want to use (e.g., '6.0.x' for .NET 6)
    includePreviewVersions: false  # Set to true if you want to include preview versions

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/WebApplication1Tests/*.csproj'
    arguments: '--configuration Release --collect "Code coverage"'
    publishTestResults: true
    publishCodeCoverage: true

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll_file'
    publishLocation: 'Container'

- task: PowerShell@2
  displayName: 'GET Request'
  inputs:
    targetType: inline
    script: |
        $uri = "https://codeanalysis.azurewebsites.net/CodeAnalysis/GetName"
        try {
            $response = Invoke-RestMethod -Uri $uri -Method Get
            echo $response
        } catch {
            Write-Error "Failed to make GET request: $_"
            exit 1
        }

- task: PowerShell@2
  displayName: 'POST Request'
  inputs:
    targetType: inline
    script: |
        # Define the URL for the POST request
        $uri = "https://codeanalysis.azurewebsites.net/CodeAnalysis/Post"

        # Define the JSON payload to send in the request body
        $jsonPayload = @{
            age = 34
            name = "Navtish"
        } | ConvertTo-Json

        # Send the POST request with the JSON payload
        try {
            $response = Invoke-RestMethod -Uri $uri -Method Post -ContentType 'application/json' -Body $jsonPayload
            echo $response
        } catch {
            Write-Error "Failed to send POST request: $_"
            exit 1
        }
