trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs: 
    targetType: inline
    script: |
        $uri = "https://jsonplaceholder.typicode.com/posts/1"
        $response = Invoke-RestMethod -Uri $uri -Method Get
        echo $response