trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    $filePath = "Common"
    if (-not (Test-Path $filePath)) {
        Write-Output "The file '$filePath' does not exist."
        exit 1  # Fail the task
    } else {
        Write-Output "The file '$filePath' exists."
    }
  displayName: 'Check File Existence'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/WebApplication1Tests/*.csproj'
    arguments: '--configuration Release --collect "Code coverage"'
    publishTestResults: true
    publishCodeCoverage: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll_file'
    publishLocation: 'Container'

- powershell: |
    # Define the API endpoint URL
    $apiUrl = 'https://localhost:7182/Student/getAll'

    # Retrieve API token from environment variable
    $apiToken = $env:API_TOKEN

    # Set up HTTP headers
    $headers = @{
        "Authorization" = "Bearer $apiToken"
        "Content-Type" = "application/json"
    }

    try {
        # Send GET request to API endpoint
        $response = Invoke-RestMethod -Uri $apiUrl -Method Get -Headers $headers

        # Parse the JSON response
        $parsedResponse = $response | ConvertFrom-Json

        # Extract and process data from the parsed response
        $extractedData = $parsedResponse.data  # Adjust the property based on the API's response structure
        Write-Output "Extracted data: $extractedData"

    } catch [System.Net.WebException] {
        Write-Error "Network error occurred: $_"
        exit 1
    } catch {
        # Handle other exceptions
        Write-Error "Failed to call API: $_"
        exit 1
    }
  displayName: 'Call API and Process Data'
